### ISSUE TITLE
Test - Rest API

### ISSUE THREAD

**Issue by Dan-Amaral** [Dan-Amaral/RView#1]
Hi Max,

I'm having some problems with the final version of rest API, can you take a look in it?

Thanks,

Daniel

**Comment by Maxgrb** [comment]
Hi @Dan-Amaral, what type of problems do you have?

**Comment by Dan-Amaral** [comment]
Hello! I'm trying to find one solution to make the rest API login part  
good. I already made the login fonction by myself, but isn't working  
properly. If you can take a look it's gonna be helpful. It' in the  
back-end part.

Thanks!


Max Gorbachev <notifications@github.com> a écrit :

**Comment by Maxgrb** [comment]
Hey @Dan-Amaral I would be happy to help, but I'm not a back-end developer. I can discuss anything regarding UI design and front-end, but not a server side. Sorry...

**Comment by Dan-Amaral** [comment]
Understood. I'm trying to talk to anothers back-end devs too. But  
thanks for the fast answer anyway.

Daniel

Max Gorbachev <notifications@github.com> a écrit :
